### PR TITLE
Fix try_from for stable rust

### PR DESCRIPTION
**Pull request by timokoesters**
try_from is stable now, the feature is not necessary anymore

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
Thanks for the PR @timokoesters! Would you also be able to remove the `try_from` feature from `Cargo.toml` and any other references to `feature = "try_from"`?

**Comment by timokoesters** [comment]
@Michael-F-Bryan Like this?

**Comment by Michael-F-Bryan** [comment]
@timokoesters that's awesome, thanks a lot!

**Comment by Michael-F-Bryan** [comment]
This is technically a breaking release because we've removed a feature flag, so I've pushed `v.0.2.0` to to crates.io.

**Pull request merged**
